# This workflow will build a Java project with Maven 
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

#ワークフロー名を「Java CI with Maven」に設定
name: Build and Push

#masterブランチへのpush時にこのワークフローを実行するよう指定
on:
  push:
    branches: 
      - 'main'
    tags:
      - 'v*'

#以下JOB
jobs:
  #ジョブ名(build)を設定
  ci:
    #ジョブの実行環境
    runs-on: ubuntu-latest

# Dockerコンテナに変数を渡す挙動をDockerCompose側に移動
#    env:
#      SPRING_DATASOURCE_URL: ${{ secrets.URL }}
#      SPRING_DATASOURCE_USERNAME: ${{ secrets.USERNAME }}
#      SPRING_DATASOURCE_PASSWORD: ${{ secrets.PASSWORD }}
#      SPRING_DATASOURCE_DRIVERCLASSNAME:  ${{ secrets.DRIVER }}

    #実行する処理やコマンドを指定
    steps:
    - uses: actions/checkout@v2 #リポジトリからのチェックアウトを行う「actions/checkout」アクションを実行する

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11.0.6'

    - name: Maven purge
      run: ./mvnw dependency:purge-local-repository -DreResolve=false -f springtaskapp-parent/pom.xml

    - name: Build and Test with Maven
      run: ./mvnw clean package -f springtaskapp-parent/pom.xml

    #
    #ここからDocker
    #
    #- name: Set up Docker Buildx
    #  uses: docker/setup-buildx-action@v1

    #Tagなどを作成するためのいろんなmetaデータを取得する
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: keropon48/springtaskapp

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    #BuildやPushの方法を変更しました
    #- name: Build, tag, and push image to Github
    #  env:
    #    DOCKERHUB_REPOSITORY: springtaskapp
    #  run: |
    #    docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/$DOCKERHUB_REPOSITORY:${{ steps.meta.outputs.tags }} springtaskapp-spring
    #    docker push ${{ secrets.DOCKERHUB_USERNAME }}/$DOCKERHUB_REPOSITORY:${{ steps.meta.outputs.tags }}

    # Docker公式で用意されているモジュールがあったため使用。
    # これでやると疎結合にできないけど、面倒なのでこれで実装
    # 参考：https://github.com/marketplace/actions/docker-metadata-action
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./springtaskapp-spring
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
# Dockerコンテナに変数を渡す挙動をDockerCompose側に移動
#        build-args: |
#            url=${{ secrets.URL }}
#            username=${{ secrets.USERNAME }}
#            password=${{ secrets.PASSWORD }}
#            driver=${{ secrets.DRIVER }}

    # 参考：https://github.com/peter-evans/repository-dispatch#token
    - name: dispatch update-pkgs
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.GIT_ACCESS_TOKEN }}
        repository: Yumapon/DockerCompose_ECS
        event-type: update-pkgs
        client-payload: '{"part": "back", "imagetag": "${{ github.ref }}"}'
        